# Generated by Django 4.2 on 2023-06-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasariteuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projectparasite',
            old_name='user_id',
            new_name='user',
        ),
    ]
