# Generated by Django 4.2 on 2023-05-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_projectuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuser',
            old_name='Project',
            new_name='project',
        ),
    ]
