# Generated by Django 4.2 on 2023-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_assiciatecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='assiciatecompany',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
