# Generated by Django 4.2 on 2023-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_user_delete_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModels',
        ),
    ]
