# Generated by Django 4.2 on 2023-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_rename_user_usermodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
