# Generated by Django 4.2 on 2023-05-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_project_projectuser_project'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorities',
            name='company',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
    ]
