# Generated by Django 4.2 on 2023-05-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_assiciatecompany'),
        ('ticket', '0002_priorities_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='priorities',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
