# Generated by Django 4.2 on 2023-05-20 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_foreignuser'),
        ('ticket', '0004_alter_attachments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.project'),
            preserve_default=False,
        ),
    ]
