# Generated by Django 4.2 on 2023-05-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_tickets_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='project_name',
            new_name='project',
        ),
    ]
