# Generated by Django 4.2 on 2023-05-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rename_project_name_tickets_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='project',
            new_name='prj',
        ),
    ]
