# Generated by Django 4.2 on 2023-05-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_messagemodel_attachments_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='ticket',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets'),
            preserve_default=False,
        ),
    ]
