# Generated by Django 4.2 on 2023-05-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_attachments_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='message',
        ),
        migrations.CreateModel(
            name='MessageAttachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.messagemodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets')),
            ],
        ),
    ]
