# Generated by Django 4.2 on 2023-05-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_tickets_closed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.CharField(blank=True, max_length=384000, null=True),
        ),
    ]
